/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.sis.java-conventions")
    war
}

dependencies {
    providedCompile("javax:javaee-api:8.0.1")
}

group = "org.apache.sis.application"
description = "Apache SIS web services layer"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
