/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.sis.java-conventions")
}

dependencies {
    implementation("org.opengis:geoapi-pending:4.0-SNAPSHOT")
    implementation(project(":core:sis-referencing"))
    implementation(project(":core:sis-metadata"))
    compileOnly("org.libreoffice:libreoffice:7.3.3")
}

group = "org.apache.sis.application"
description = "Bridges to Apache OpenOffice or LibreOffice"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
