/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.sis.java-conventions")
}

dependencies {
    compileOnly(drivers.postgres)

    implementation(project(":storage:sis-storage"))

    testImplementation(libs.geometry.esri)
    testImplementation(libs.geometry.jts)

    testRuntimeOnly(drivers.h2)
    testRuntimeOnly(drivers.hsqldb)
    testRuntimeOnly(drivers.postgres)
}

group = "org.apache.sis.storage"
description = "Apache SIS SQL storage"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
