/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.sis.java-conventions")
}

dependencies {
    implementation(project(":storage:sis-netcdf"))
    implementation("edu.ucar:cdm-core:5.5.3")
    runtimeOnly("org.slf4j:slf4j-jdk14:1.7.28")
}

group = "org.apache.sis.profiles"
description = "Apache SIS Japanese profiles"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
