/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.sis.java-conventions")
}

dependencies {
    implementation(project(":core:sis-feature"))
    compileOnly(libs.geometry.jts)
    implementation("org.antlr:antlr4-runtime:4.10.1")
    testImplementation(project(":core:sis-utility"))
}

group = "org.apache.sis.core"
description = "Apache SIS CQL"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
