/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.sis.java-conventions")
}

dependencies {
    // Should be runtime after the hack in FormattedOutputCommand has been fixed.
    implementation(project(":storage:sis-xmlstore"))
    runtimeOnly(project(":storage:sis-netcdf"))
    runtimeOnly(project(":storage:sis-geotiff"))
    runtimeOnly(project(":storage:sis-earth-observation"))
    runtimeOnly(drivers.derby)

    testImplementation(project(":core:sis-metadata"))
    testImplementation(project(":storage:sis-xmlstore"))
    testRuntimeOnly(libs.jaxb.runtime)
}

group = "org.apache.sis.application"
description = "Apache SIS console"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
