/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.sis.java-conventions")
}

dependencies {
    implementation("org.sonatype.plexus:plexus-build-api:0.0.7")
    implementation("org.apache.commons:commons-compress:1.21")
    compileOnly("org.apache.maven:maven-core:3.8.5")
    compileOnly("org.apache.maven:maven-plugin-api:3.8.5")
    compileOnly("org.apache.maven.plugin-tools:maven-plugin-annotations:3.6.4")
}

group = "org.apache.sis.core"
description = "Apache SIS build helper"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
