/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.sis.java-conventions")
}

dependencies {
    api(project(":core:sis-metadata"))

    testImplementation(rootProject.libs.geographiclib)
    testImplementation(rootProject.libs.jama)

    testRuntimeOnly(rootProject.libs.jaxb.runtime)

    testRuntimeOnly(rootProject.drivers.h2)
    testRuntimeOnly(rootProject.drivers.hsqldb)
    testRuntimeOnly(rootProject.drivers.postgres)
}

group = "org.apache.sis.core"
description = "Apache SIS referencing"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
