/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.sis.java-conventions")
}

dependencies {
    api(libs.jaxb.api)

    api(project(":core:sis-utility"))

    testImplementation(project(":core:sis-utility", "testArtifact"))

    testRuntimeOnly(libs.jaxb.runtime)

    testRuntimeOnly(drivers.h2)
    testRuntimeOnly(drivers.hsqldb)
    testRuntimeOnly(drivers.postgres)
}

group = "org.apache.sis.core"
description = "Apache SIS metadata"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
