/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.sis.java-conventions")
}

dependencies {
    implementation("software.amazon.awssdk:s3:2.17.185")
    implementation(project(":core:sis-utility"))
}

group = "org.apache.sis.cloud"
description = "Apache SIS storage from Amazon AWS S3"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
