/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.sis.java-conventions")
}

dependencies {
    api(project(":storage:sis-storage"))
    testImplementation(project(":storage:sis-storage"))
    testImplementation("org.slf4j:slf4j-jdk14:1.7.28")
    compileOnly("edu.ucar:cdm-core:5.5.3")
}

group = "org.apache.sis.storage"
description = "Apache SIS netCDF storage"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
