/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.sis.java-conventions")
}

dependencies {
    implementation(project(":core:sis-metadata"))
    testImplementation(project(":core:sis-metadata"))
    testRuntimeOnly(libs.jaxb.runtime)
}

group = "org.apache.sis.profiles"
description = "Apache SIS French profiles"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
