/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.sis.java-conventions")
}

dependencies {
    api(project(":core:sis-referencing"))

    testImplementation(project(":core:sis-utility"))
    testImplementation(project(":core:sis-metadata"))
    testImplementation(project(":core:sis-referencing"))
    testRuntimeOnly(drivers.derby)
}

group = "org.apache.sis.core"
description = "Apache SIS referencing by geographic identifiers"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
