/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.sis.java-conventions")
}

dependencies {
    compileOnly("org.osgi:org.osgi.core:6.0.0")
    compileOnly("javax:javaee-api:8.0.1")
}

group = "org.apache.sis.core"
description = "Apache SIS utilities"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

configurations.create("testArtifact") {
    artifacts { testsJar }
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
