/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.sis.java-conventions")
}

dependencies {
    implementation(project(":storage:sis-geotiff"))
}

group = "org.apache.sis.storage"
description = "Apache SIS Earth Observation storage"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
