/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.apache.sis.java-conventions")
}

dependencies {
    api(project(":storage:sis-storage"))
    compileOnly(libs.geometry.esri)
}

group = "org.apache.sis.storage"
description = "Apache SIS Shapefile storage"

val testsJar by tasks.registering(Jar::class) {
    archiveClassifier.set("tests")
    from(sourceSets["test"].output)
}

(publishing.publications["maven"] as MavenPublication).artifact(testsJar)
